name: splash_screen
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/splash/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/logo.png
  branding: assets/splash/branding.png
  color_dark: "#121212"
  image_dark: assets/splash/logo_dark.png
  branding_dark: assets/splash/branding_dark.png

  android_12:
    image: assets/splash/android_12/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash/logo_dark.png
    icon_background_color_dark: "#121212"
    branding: assets/splash/android_12/branding.png
    branding_dark: assets/splash/android_12/branding_dark.png

  web: false